
from dataclasses import dataclass
from pathlib import Path
import json

from core.build_readiness import BuildReadinessAnalyzer
from core.jar_builder import JarBuilder
from core.regression_validator import RegressionValidator
from core.runtime_test_packager import RuntimeTestPackager

@dataclass
class StableBuildResult:
    status: str
    output_jar: str = ""
    build_report_path: str = ""
    regression_report_path: str = ""
    runtime_folder: str = ""
    runtime_zip: str = ""
    message: str = ""

class StablePipeline:
    """Stable integration point: readiness -> build -> regression -> runtime package."""

    def readiness(self, result, project):
        return BuildReadinessAnalyzer().analyze(result, project)

    def build(self, result, project, output_path: str, allow_warnings: bool=False) -> StableBuildResult:
        ready = self.readiness(result, project)

        if ready.status == "BLOCKED":
            reasons = "; ".join(i.message for i in ready.issues if i.level == "BLOCKED")
            return StableBuildResult("BLOCKED", message=reasons)

        if ready.status == "WARNING" and not allow_warnings:
            reasons = "; ".join(i.message for i in ready.issues if i.level == "WARNING")
            return StableBuildResult("WARNING", message=reasons)

        build_report = JarBuilder().build(result, project, output_path)
        build_report_path = str(Path(output_path).with_suffix(".build-report.json"))
        build_report.save_json(build_report_path)

        rr = RegressionValidator().validate(result, project, output_path)
        regression_report_path = str(Path(output_path).with_suffix(".regression-report.json"))
        Path(regression_report_path).write_text(
            json.dumps({
                "source_jar": rr.source_jar,
                "output_jar": rr.output_jar,
                "archive_ok": rr.archive_ok,
                "rescan_ok": rr.rescan_ok,
                "validation_ok": rr.validation_ok,
                "passed": rr.passed,
                "failed": rr.failed,
                "skipped": rr.skipped,
                "warnings": rr.warnings,
                "items": [i.__dict__ for i in rr.items],
            }, ensure_ascii=False, indent=2),
            encoding="utf-8"
        )

        ok = bool(build_report.validation_ok and build_report.regression_ok and rr.validation_ok)
        return StableBuildResult(
            "PASS" if ok else "FAIL",
            output_jar=str(output_path),
            build_report_path=build_report_path,
            regression_report_path=regression_report_path,
            message=(
                f"patched={build_report.patched}, failed={build_report.failed}, "
                f"regression_passed={rr.passed}, regression_failed={rr.failed}"
            )
        )

    def create_runtime_package(self, build_result: StableBuildResult, source_jar: str, destination_dir: str):
        if build_result.status != "PASS":
            raise ValueError("Runtime package is only created from a PASS build.")

        pkg = RuntimeTestPackager().create(
            source_jar,
            build_result.output_jar,
            destination_dir,
            build_result.build_report_path,
            build_result.regression_report_path,
            notes="Generated by JAR Vietnamese Translator V4.6"
        )
        build_result.runtime_folder = pkg.folder
        build_result.runtime_zip = pkg.zip_path
        return build_result
